spring:
  application:
    name: web-service
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false
    prefix: classpath:/web-server/templates/

error:
  path=/error

eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/

# HTTP Server
server:
  port: 4002   # HTTP (Tomcat) port
